### PR TITLE
Deprecate `--only` and `--except`

### LINKED ISSUE #25: Remove `--except` and rename `--only` to `--rules`
Most tools make you explicitly whitelist params.  This is nice because then you avoid the possibility of your project automatically picking up a new rule and starting to fail.  Also, technically each release that adds a new rule would likely be a "breaking change" requiring a major release.  Thoughts?

### PR DESCRIPTION
**Pull request by cjoudrey**
Fixes #25

We are favouring whitelists as it will make it easier for us to introduce new rules without it being a breaking change for existing users.

There is a bit of code duplication in this PR but it is okay since we will be :fire: the code in the coming days/weeks as we release v1.0.0.

cc @goldcaddy77

### CODE REVIEW

File: src/configuration.js [hunk 1]
```diff
@@ -68,28 +80,18 @@ export class Configuration {
...
     sync: true,
   }).load(searchPath);
-  let options = {};
+
   if (cosmic) {
-    // Map config.rules -> `only` param
-    if (cosmic.config.rules) {
-      options.only = cosmic.config.rules;
-    }
+    return cosmic.config;
```
Comment (goldcaddy77) [inline src/configuration.js]: We'd want to return `{options: cosmic.config}` here, right?

**Comment by goldcaddy77** [comment]
:shipit:

File: src/configuration.js (hunk 1 above)
Comment (cjoudrey) [inline src/configuration.js]: That's a good point. It might be more prudent to start with a whitelist first. I'll make the change.
