### PR TITLE
fix(source-maps): add support for node 6

### LINKED ISSUE #44: Object.values is not a function
`Object.values` doesn't seem to be supported in the [LTS version of Node](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values).  We should use a workaround [like this](https://stackoverflow.com/a/38748490) so that we support Node 6.

### PR DESCRIPTION
**Pull request by goldcaddy77**
Fixes #44 

`Object.values` doesn't seem to be supported in the [LTS version of Node](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values).  We should use a workaround [like this](https://stackoverflow.com/a/38748490) so that we support Node 6.

### CODE REVIEW

**Comment by cjoudrey** [comment]
Good catch. Had no idea `Object.values` wasn't available in older versions of `node`.

I'm going to modify `.travis.yml` so that we test against a few more versions.

File: src/source_map.js [hunk 1]
```diff
@@ -29,11 +29,11 @@ export class SourceMap {
   }
 
   getCombinedSource() {
-    return Object.values(this.sourceFiles).join('\n');
```
Comment (cjoudrey) [inline src/source_map.js]: Since we're already using `babel`, is there no way for `babel` to include a `Object.values` polyfill? I remember seeing this somewhere. 🤔

**Comment by cjoudrey** [comment]
Feel free to add this to your PR to prevent this from happening again: https://github.com/cjoudrey/graphql-schema-linter/commit/d5c7353b12899c661d38237b85605c381a1b8b52

File: .travis.yml [hunk 2]
```diff
@@ -1,3 +1,4 @@
 language: node_js
 node_js:
   - "node"
+  - "lts/*"
```
Comment (goldcaddy77) [inline .travis.yml]: @cjoudrey done.

File: src/source_map.js (hunk 1 above)
Comment (goldcaddy77) [reply src/source_map.js]: There might be a Babel plugin, but this is simple enough.  Lemme know if you want me to dig deeper.

Comment (cjoudrey) [reply src/source_map.js]: I was mostly worried about us needing `Object.values` elsewhere at some point.

I suppose we could solve that if/when we reach that point.

**Comment by cjoudrey** [comment]
Thanks again for the fix! :+1: 😁
